"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { CatalogProduct, ProductBlock, ProductVariant } from "@/lib/catalog/types";
import { useCart } from "@/contexts/CartContext";
import styles from "./ProductDetail.module.css";
const money = new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 });
const order = ["richText", "benefitCards", "ingredientCards", "featureGrid", "howToUse", "treatmentJourney", "comparisonTable", "certifications", "faq", "reviews"];
const items = (block: ProductBlock) => Array.isArray(block.data.items) ? block.data.items as Array<Record<string, unknown>> : [];
export function ProductDetail({ product }: { product: CatalogProduct }) {
  const router = useRouter(); const { addItem } = useCart(); const [selected, setSelected] = useState<Record<string, string>>({}); const [phone, setPhone] = useState(""); const [phoneOpen, setPhoneOpen] = useState(false); const [pendingBuy, setPendingBuy] = useState(false); const [selectedImage, setSelectedImage] = useState(0);
  const selectedOptions = useMemo(() => product.optionGroups.map((group) => { const option = group.options.find((entry) => entry.value === selected[group.code]); return option ? { groupCode: group.code, groupTitle: group.title, optionValue: option.value, optionLabel: option.label, priceAdjustment: option.priceAdjustment ?? 0 } : null; }).filter(Boolean) as { groupCode: string; groupTitle: string; optionValue: string; optionLabel: string; priceAdjustment: number }[], [product, selected]);
  const matchedVariant = useMemo<ProductVariant | undefined>(() => product.variants.find((variant) => Object.entries(variant.optionValues ?? {}).every(([code, value]) => selected[code] === value)), [product.variants, selected]);
  const price = useMemo(() => matchedVariant?.price ?? product.price + selectedOptions.reduce((total, option) => total + option.priceAdjustment, 0), [matchedVariant, product.price, selectedOptions]);
  const blocks = product.blocks.filter((block) => block.isActive).sort((a, b) => order.indexOf(a.type) - order.indexOf(b.type));
  async function addToCart(buyNow: boolean) { const missing = product.optionGroups.find((group) => group.required && !selected[group.code]); if (missing) { window.alert(`Vui lòng chọn ${missing.title}.`); return; } addItem({ productId: product.id, name: product.name, price, image: product.images[0] ?? "", variantId: matchedVariant?.id ?? "", variantTitle: matchedVariant?.title ?? selectedOptions.map((option) => option.optionLabel).join(" / "), options: selectedOptions }); if (buyNow) router.push("/checkout"); }
  function start(buyNow: boolean) { setPendingBuy(buyNow); setPhone(window.localStorage.getItem("toctai_guest_phone") ?? ""); setPhoneOpen(true); }
  function confirmPhone(event: React.FormEvent) { event.preventDefault(); if (!/^0[0-9]{9,10}$/.test(phone.replace(/\s/g, ""))) return; window.localStorage.setItem("toctai_guest_phone", phone.replace(/\s/g, "")); setPhoneOpen(false); void addToCart(pendingBuy); }
  return <main className={styles.page}><div className={styles.crumbs}>{"Trang ch\u1ee7"} / {product.category} / {product.name}</div><div className={styles.purchase}><section className={styles.gallery}><div className={styles.thumbs}>{product.images.slice(0, 4).map((image, index) => <button className={styles.thumb} key={image} aria-label={`Anh san pham ${index + 1}`} style={{ backgroundImage: `url(${image})` }} onClick={() => setSelectedImage(index)} />)}</div><div className={styles.image}>{product.images[selectedImage] ? <img src={product.images[selectedImage]} alt={product.name} /> : <span>{product.category.toUpperCase()}</span>}</div></section><section className={styles.summary}><p className={styles.eyebrow}>{product.shortDescription}</p><h1>{product.name}</h1><div className={styles.rating}>★ {product.rating ?? "—"}<span>{product.reviewCount ?? 0} {"\u0111\u00e1nh gi\u00e1"} · {product.soldCount ?? 0} {"\u0111\u00e3 b\u00e1n"}</span></div><div className={styles.price}>{money.format(price)} <del>{money.format(product.compareAtPrice ?? price)}</del></div>{product.optionGroups.map((group) => <fieldset className={styles.options} key={group.id}><legend>{group.title}</legend><div className={group.displayType === "card" ? styles.cards : styles.optionRow}>{group.options.map((option) => <button type="button" className={selected[group.code] === option.value ? styles.selected : ""} key={option.id} onClick={() => setSelected((current) => ({ ...current, [group.code]: option.value }))}>{option.label}{option.priceAdjustment ? ` (+${money.format(option.priceAdjustment)})` : ""}</button>)}</div></fieldset>)}<div className={styles.actions}><button type="button" onClick={() => start(false)}>{"Th\u00eam v\u00e0o gi\u1ecf"}</button><button type="button" onClick={() => start(true)}>{"Mua ngay"}</button></div><div className={styles.delivery}><b>{"C\u00f3 h\u1ed7 tr\u1ee3 giao h\u00e0ng"}</b><br />{"Nh\u1eadp s\u1ed1 \u0111i\u1ec7n tho\u1ea1i \u0111\u1ec3 ti\u1ebfp t\u1ee5c mua h\u00e0ng."}</div></section></div><div className={styles.blocks}>{blocks.map((block) => <Block key={block.id} block={block} />)}</div>{phoneOpen && <div className={styles.modalBackdrop}><form className={styles.phoneModal} onSubmit={confirmPhone}><h2>{"X\u00e1c nh\u1eadn s\u1ed1 \u0111i\u1ec7n tho\u1ea1i"}</h2><p>{"S\u1ed1 \u0111i\u1ec7n tho\u1ea1i d\u00f9ng \u0111\u1ec3 x\u00e1c nh\u1eadn \u0111\u01a1n v\u00e0 giao h\u00e0ng."}</p><input autoFocus required inputMode="tel" value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="0901234567" /><div><button type="button" onClick={() => setPhoneOpen(false)}>{"H\u1ee7y"}</button><button type="submit">{"Ti\u1ebfp t\u1ee5c"}</button></div></form></div>}</main>;
}
function Block({ block }: { block: ProductBlock }) { const data = block.data; if (block.type === "richText") return <section className={styles.block}><h2>{block.title}</h2>{(data.paragraphs as string[]).map((p) => <p key={p}>{p}</p>)}</section>; if (["benefitCards", "featureGrid", "ingredientCards"].includes(block.type)) return <section className={styles.block}><h2>{block.title}</h2><div className={styles.grid}>{items(block).map((item, index) => <article key={index}><span>✦</span><h3>{String(item.title ?? item.name)}</h3>{item.description !== undefined && <p>{String(item.description)}</p>}</article>)}</div></section>; if (block.type === "howToUse" || block.type === "treatmentJourney") { const steps = Array.isArray(data.steps) ? data.steps as Array<Record<string, unknown>> : items(block); return <section className={styles.block}><h2>{block.title}</h2><div className={styles.steps}>{steps.map((item, index) => <article key={index}><b>{String(item.period ?? `Buoc ${index + 1}`)}</b><h3>{String(item.title ?? "")}</h3>{item.description !== undefined && <p>{String(item.description)}</p>}</article>)}</div></section>; } if (block.type === "comparisonTable") return <section className={styles.block}><h2>{block.title}</h2><div className={styles.compare}>{(data.rows as Array<Record<string, unknown>>).map((item, index) => <div key={index}><span>{String(item.feature)}</span><b>{item.ours ? "✓" : "—"}</b><em>{item.others ? "✓" : "—"}</em></div>)}</div></section>; if (block.type === "faq") return <section className={styles.block}><h2>{block.title}</h2>{items(block).map((item, index) => <details key={index}><summary>{String(item.question)}</summary><p>{String(item.answer)}</p></details>)}</section>; if (block.type === "reviews") return <section className={styles.block}><h2>{block.title}</h2><div className={styles.reviewScore}>★ {String(data.rating)} <span>{String(data.count)} {"đánh giá"}</span></div>{items(block).map((item, index) => <article className={styles.review} key={index}><b>{String(item.author)}</b><h3>{String(item.title)}</h3><p>{String(item.body)}</p></article>)}</section>; return null; }
