"use client";
import { useMemo, useState } from "react";
import styles from "./HairConsultationFlow.module.css";

type Screen = "intro" | "details" | "questions" | "upload" | "schedule" | "success";
type FormState = { fullName: string; phone: string; email: string; hairLoss: string; concern: string; duration: string; scalp: string; images: string[]; mode: "now" | "schedule"; language: string; date: string; time: string };
const questions = [
  ["hairLoss", "Which of the following best describes your hair loss?", ["Stage 1 hair fall", "Stage 2 hair fall", "Stage 3 hair fall", "Not sure"]],
  ["concern", "What would you like help with today?", ["Hair fall", "Thinning hair", "Dandruff & flaking", "Overall hair health"]],
  ["duration", "How long have you noticed this concern?", ["Less than 3 months", "3–6 months", "6–12 months", "More than a year"]],
  ["scalp", "How would you describe your scalp?", ["Oily", "Dry", "Itchy or flaky", "Balanced"]],
] as const;

export function HairConsultationFlow() {
  const [screen, setScreen] = useState<Screen>("intro");
  const [question, setQuestion] = useState(0);
  const [error, setError] = useState("");
  const [saved, setSaved] = useState<{ id: string; result: { recommendation: string; message: string } } | null>(null);
  const [form, setForm] = useState<FormState>({ fullName: "", phone: "", email: "", hairLoss: "", concern: "", duration: "", scalp: "", images: [], mode: "now", language: "English", date: "", time: "" });
  const current = questions[question];
  const value = form[current[0]];
  const set = (key: keyof FormState, value: string | string[]) => setForm((prev) => ({ ...prev, [key]: value }));
  const progress = useMemo(() => ({ intro: 0, details: 20, questions: 20 + question * 15, upload: 80, schedule: 90, success: 100 }[screen]), [question, screen]);
  async function upload(file: File) { setError(""); const body = new FormData(); body.append("file", file); const response = await fetch("/api/consultations/upload", { method: "POST", body }); const json = await response.json(); if (!response.ok) { setError(json.error ?? "Upload failed"); return; } set("images", [...form.images, json.data.url]); }
  async function submit() { setError(""); const response = await fetch("/api/consultations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ customer: { fullName: form.fullName, phone: form.phone, email: form.email }, category: "hair", answers: { hairLoss: form.hairLoss, concern: form.concern, duration: form.duration, scalp: form.scalp }, images: form.images, appointment: { mode: form.mode, language: form.language, date: form.date, time: form.time } }) }); const json = await response.json(); if (!response.ok) { setError(json.error ?? "Unable to submit consultation"); return; } setSaved(json.data); setScreen("success"); }
  const header = (back?: () => void, label = "Hair assessment") => <header><button className={styles.back} onClick={back}>←</button><b>Man Matters</b><span>{label}</span></header>;
  if (screen === "intro") return <main className={styles.page}>{header()}<section className={styles.intro}><div className={styles.illustration}>✦<i>✓</i></div><p className={styles.kicker}>PERSONALISED HAIR CARE</p><h1>Let’s understand your hair better</h1><p>Answer some basic health questions, upload images and claim a FREE doctor consult.</p><button className={styles.primary} onClick={() => setScreen("details")}>Let&apos;s Begin <span>→</span></button><small>It takes less than a minute</small></section></main>;
  if (screen === "details") return <main className={styles.page}>{header(() => setScreen("intro"), "Basic details")}<section className={styles.form}><Progress value={progress} /><p className={styles.kicker}>SHARE BASIC DETAILS</p><h1>How can our doctor reach you?</h1><p className={styles.muted}>Your details stay private and help us create a personalised plan.</p><label>Full name<input value={form.fullName} onChange={(e) => set("fullName", e.target.value)} placeholder="Enter your name" /></label><label>Phone number<input value={form.phone} onChange={(e) => set("phone", e.target.value)} placeholder="10-digit phone number" inputMode="tel" /></label><label>Email (optional)<input value={form.email} onChange={(e) => set("email", e.target.value)} placeholder="you@example.com" /></label><button className={styles.next} disabled={!form.fullName || form.phone.length < 10} onClick={() => setScreen("questions")}>Continue <span>→</span></button>{error && <p className={styles.error}>{error}</p>}</section></main>;
  if (screen === "questions") return <main className={styles.page}>{header(() => setScreen(question === 0 ? "details" : "questions"), `${question + 1} of ${questions.length}`)}<section className={styles.form}><Progress value={progress} /><p className={styles.kicker}>HAIR LOSS ASSESSMENT</p><h1>{current[1]}</h1><p className={styles.muted}>Choose the option that feels closest to your current concern.</p><div className={styles.options}>{current[2].map((answer) => <button className={value === answer ? styles.selected : ""} key={answer} onClick={() => set(current[0], answer)}><span>{answer}</span>{value === answer && <b>✓</b>}</button>)}</div><button className={styles.next} disabled={!value} onClick={() => question === questions.length - 1 ? setScreen("upload") : setQuestion(question + 1)}>{question === questions.length - 1 ? "Upload images" : "Next"} <span>→</span></button></section></main>;
  if (screen === "upload") return <main className={styles.page}>{header(() => setScreen("questions"), "Upload images")}<section className={styles.form}><Progress value={progress} /><p className={styles.kicker}>UPLOAD IMAGES</p><h1>{form.images.length === 0 ? "Upload Images" : form.images.length === 1 ? "Great Going, 1 more to go!" : "All set for your consultation"}</h1><p className={styles.muted}>Uploading images is necessary as it helps the doctor assess your condition better.</p><div className={styles.uploadGrid}><Upload title="Hairline" onChange={upload} done={Boolean(form.images[0])} /><Upload title="Crown" onChange={upload} done={Boolean(form.images[1])} /></div><p className={styles.skip} onClick={() => setScreen("schedule")}>Skip Image Upload?</p><button className={styles.next} disabled={form.images.length < 2} onClick={() => setScreen("schedule")}>Continue <span>→</span></button>{error && <p className={styles.error}>{error}</p>}</section></main>;
  if (screen === "schedule") return <main className={styles.page}>{header(() => setScreen("upload"), "Book your doctor")}<section className={styles.form}><Progress value={progress} /><p className={styles.kicker}>FREE CONSULT IN 3–5 MINUTES</p><h1>Talk to a doctor about your hair</h1><div className={styles.mode}><button className={form.mode === "now" ? styles.selected : ""} onClick={() => set("mode", "now")}>Talk to Doctor Now<small>Doctor will call within 3–5 mins</small></button><button className={form.mode === "schedule" ? styles.selected : ""} onClick={() => set("mode", "schedule")}>Schedule an appointment<small>Choose a convenient time</small></button></div>{form.mode === "schedule" && <div className={styles.row}><label>Language<select value={form.language} onChange={(e) => set("language", e.target.value)}><option>English</option><option>Hindi</option><option>Tamil</option></select></label><label>Date<input type="date" value={form.date} onChange={(e) => set("date", e.target.value)} /></label><label>Time<input type="time" value={form.time} onChange={(e) => set("time", e.target.value)} /></label></div>}<button className={styles.next} onClick={submit}>Confirm consultation <span>→</span></button>{error && <p className={styles.error}>{error}</p>}</section></main>;
  return <main className={styles.page}>{header(undefined, "Appointment confirmed")}<section className={styles.success}><div className={styles.successMark}>✓</div><p className={styles.kicker}>THANK YOU FOR COMPLETING THE ASSESSMENT</p><h1>All set for your consultation</h1><p>Your answers and images have been submitted. {saved?.result.message}</p><div className={styles.result}><b>Your focus</b><span>{form.concern || form.hairLoss}</span><b>Recommended starting point</b><span>{saved?.result.recommendation}</span><b>Consultation ID</b><span>{saved?.id}</span></div><button className={styles.primary} onClick={() => setScreen("intro")}>Start again</button></section></main>;
}
function Progress({ value }: { value: number }) { return <div className={styles.progress}><i style={{ width: `${value}%` }} /></div>; }
function Upload({ title, done, onChange }: { title: string; done: boolean; onChange: (file: File) => void }) { return <label className={styles.uploadCard}><div className={styles.uploadIcon}>{done ? "✓" : "＋"}</div><b>{done ? `${title} image uploaded` : `Upload ${title}`}</b>{!done && <><span>JPG, PNG or WEBP · max 10MB</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => { const file = e.target.files?.[0]; if (file) onChange(file); }} /></>}</label>; }
