"use client";
import { useMemo, useState } from "react";
import styles from "./HairConsultationFlow.module.css";

type Screen = "intro" | "details" | "questions" | "upload" | "schedule" | "success";
type FormState = { fullName: string; phone: string; email: string; hairLoss: string; concern: string; duration: string; scalp: string; images: string[]; mode: "now" | "schedule"; language: string; date: string; time: string };
const questions = [
  ["hairLoss", "Mô tả nào phù hợp nhất với tình trạng rụng tóc của bạn?", ["Giai đoạn 1 - Tóc bắt đầu rụng", "Giai đoạn 2 - Tóc rụng rõ hơn", "Giai đoạn 3 - Tóc thưa nhiều", "Chưa chắc chắn"]],
  ["concern", "Hôm nay bạn muốn được hỗ trợ vấn đề nào?", ["Rụng tóc", "Tóc thưa", "Gàu và bong tróc da đầu", "Sức khỏe tóc tổng thể"]],
  ["duration", "Bạn nhận thấy vấn đề này trong bao lâu rồi?", ["Dưới 3 tháng", "3-6 tháng", "6-12 tháng", "Hơn 1 năm"]],
  ["scalp", "Bạn mô tả da đầu của mình như thế nào?", ["Da đầu dầu", "Da đầu khô", "Ngứa hoặc bong tróc", "Cân bằng"]],
] as const;

export function HairConsultationFlow() {
  const [screen, setScreen] = useState<Screen>("intro");
  const [question, setQuestion] = useState(0);
  const [error, setError] = useState("");
  const [saved, setSaved] = useState<{ id: string; result: { recommendation: string; message: string } } | null>(null);
  const [form, setForm] = useState<FormState>({ fullName: "", phone: "", email: "", hairLoss: "", concern: "", duration: "", scalp: "", images: [], mode: "now", language: "Tiếng Việt", date: "", time: "" });
  const current = questions[question];
  const value = form[current[0]];
  const set = (key: keyof FormState, value: string | string[]) => setForm((prev) => ({ ...prev, [key]: value }));
  const progress = useMemo(() => ({ intro: 0, details: 20, questions: 20 + question * 15, upload: 80, schedule: 90, success: 100 }[screen]), [question, screen]);
  async function upload(file: File) { setError(""); const body = new FormData(); body.append("file", file); const response = await fetch("/api/consultations/upload", { method: "POST", body }); const json = await response.json(); if (!response.ok) { setError(json.error ?? "Tải ảnh thất bại"); return; } set("images", [...form.images, json.data.url]); }
  async function submit() { setError(""); const response = await fetch("/api/consultations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ customer: { fullName: form.fullName, phone: form.phone, email: form.email }, category: "hair", answers: { hairLoss: form.hairLoss, concern: form.concern, duration: form.duration, scalp: form.scalp }, images: form.images, appointment: { mode: form.mode, language: form.language, date: form.date, time: form.time } }) }); const json = await response.json(); if (!response.ok) { setError(json.error ?? "Không thể gửi thông tin tư vấn"); return; } setSaved(json.data); setScreen("success"); }
  const header = (back?: () => void, label = "Kiểm tra tóc") => <header><button className={styles.back} onClick={back}>←</button><b>Tóc Tai</b><span>{label}</span></header>;
  if (screen === "intro") return <main className={styles.page}>{header()}<section className={styles.intro}><div className={styles.illustration}>✦<i>✓</i></div><p className={styles.kicker}>CHĂM SÓC TÓC CÁ NHÂN HÓA</p><h1>Cùng hiểu mái tóc của bạn rõ hơn</h1><p>Trả lời vài câu hỏi cơ bản, tải ảnh lên và nhận tư vấn miễn phí từ chuyên gia.</p><button className={styles.primary} onClick={() => setScreen("details")}>Bắt đầu <span>→</span></button><small>Chỉ mất chưa đến 1 phút</small></section></main>;
  if (screen === "details") return <main className={styles.page}>{header(() => setScreen("intro"), "Thông tin cơ bản")}<section className={styles.form}><Progress value={progress} /><p className={styles.kicker}>CHIA SẺ THÔNG TIN CƠ BẢN</p><h1>Chuyên gia có thể liên hệ với bạn thế nào?</h1><p className={styles.muted}>Thông tin của bạn được bảo mật và giúp chúng tôi tạo lộ trình cá nhân hóa.</p><label>Họ và tên<input value={form.fullName} onChange={(e) => set("fullName", e.target.value)} placeholder="Nhập họ tên của bạn" /></label><label>Số điện thoại<input value={form.phone} onChange={(e) => set("phone", e.target.value)} placeholder="Số điện thoại 10 chữ số" inputMode="tel" /></label><label>Email (không bắt buộc)<input value={form.email} onChange={(e) => set("email", e.target.value)} placeholder="you@example.com" /></label><button className={styles.next} disabled={!form.fullName || form.phone.length < 10} onClick={() => setScreen("questions")}>Tiếp tục <span>→</span></button>{error && <p className={styles.error}>{error}</p>}</section></main>;
  if (screen === "questions") return <main className={styles.page}>{header(() => setScreen(question === 0 ? "details" : "questions"), `${question + 1} / ${questions.length}`)}<section className={styles.form}><Progress value={progress} /><p className={styles.kicker}>ĐÁNH GIÁ RỤNG TÓC</p><h1>{current[1]}</h1><p className={styles.muted}>Chọn lựa chọn gần nhất với tình trạng hiện tại của bạn.</p><div className={styles.options}>{current[2].map((answer) => <button className={value === answer ? styles.selected : ""} key={answer} onClick={() => set(current[0], answer)}><span>{answer}</span>{value === answer && <b>✓</b>}</button>)}</div><button className={styles.next} disabled={!value} onClick={() => question === questions.length - 1 ? setScreen("upload") : setQuestion(question + 1)}>{question === questions.length - 1 ? "Tải ảnh lên" : "Tiếp theo"} <span>→</span></button></section></main>;
  if (screen === "upload") return <main className={styles.page}>{header(() => setScreen("questions"), "Tải ảnh lên")}<section className={styles.form}><Progress value={progress} /><p className={styles.kicker}>TẢI ẢNH LÊN</p><h1>{form.images.length === 0 ? "Tải ảnh lên" : form.images.length === 1 ? "Tốt rồi, còn 1 ảnh nữa!" : "Đã sẵn sàng cho buổi tư vấn"}</h1><p className={styles.muted}>Tải ảnh lên giúp chuyên gia đánh giá tình trạng của bạn chính xác hơn.</p><div className={styles.uploadGrid}><Upload title="Đường chân tóc" onChange={upload} done={Boolean(form.images[0])} /><Upload title="Đỉnh đầu" onChange={upload} done={Boolean(form.images[1])} /></div><p className={styles.skip} onClick={() => setScreen("schedule")}>Bỏ qua tải ảnh?</p><button className={styles.next} disabled={form.images.length < 2} onClick={() => setScreen("schedule")}>Tiếp tục <span>→</span></button>{error && <p className={styles.error}>{error}</p>}</section></main>;
  if (screen === "schedule") return <main className={styles.page}>{header(() => setScreen("upload"), "Đặt lịch tư vấn")}<section className={styles.form}><Progress value={progress} /><p className={styles.kicker}>TƯ VẤN MIỄN PHÍ TRONG 3-5 PHÚT</p><h1>Trao đổi với chuyên gia về mái tóc của bạn</h1><div className={styles.mode}><button className={form.mode === "now" ? styles.selected : ""} onClick={() => set("mode", "now")}>Tư vấn ngay<small>Chuyên gia sẽ gọi trong 3-5 phút</small></button><button className={form.mode === "schedule" ? styles.selected : ""} onClick={() => set("mode", "schedule")}>Đặt lịch hẹn<small>Chọn thời gian thuận tiện</small></button></div>{form.mode === "schedule" && <div className={styles.row}><label>Ngôn ngữ<select value={form.language} onChange={(e) => set("language", e.target.value)}><option>Tiếng Việt</option><option>Tiếng Anh</option><option>Khác</option></select></label><label>Ngày<input type="date" value={form.date} onChange={(e) => set("date", e.target.value)} /></label><label>Giờ<input type="time" value={form.time} onChange={(e) => set("time", e.target.value)} /></label></div>}<button className={styles.next} onClick={submit}>Xác nhận tư vấn <span>→</span></button>{error && <p className={styles.error}>{error}</p>}</section></main>;
  return <main className={styles.page}>{header(undefined, "Đã xác nhận lịch tư vấn")}<section className={styles.success}><div className={styles.successMark}>✓</div><p className={styles.kicker}>CẢM ƠN BẠN ĐÃ HOÀN THÀNH ĐÁNH GIÁ</p><h1>Đã sẵn sàng cho buổi tư vấn</h1><p>Câu trả lời và hình ảnh của bạn đã được gửi. {saved?.result.message}</p><div className={styles.result}><b>Vấn đề bạn quan tâm</b><span>{form.concern || form.hairLoss}</span><b>Điểm bắt đầu đề xuất</b><span>{saved?.result.recommendation}</span><b>Mã tư vấn</b><span>{saved?.id}</span></div><button className={styles.primary} onClick={() => setScreen("intro")}>Làm lại</button></section></main>;
}
function Progress({ value }: { value: number }) { return <div className={styles.progress}><i style={{ width: `${value}%` }} /></div>; }
function Upload({ title, done, onChange }: { title: string; done: boolean; onChange: (file: File) => void }) { return <label className={styles.uploadCard}><div className={styles.uploadIcon}>{done ? "✓" : "＋"}</div><b>{done ? `${title} đã được tải lên` : `Tải ảnh ${title}`}</b>{!done && <><span>JPG, PNG hoặc WEBP · tối đa 10MB</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => { const file = e.target.files?.[0]; if (file) onChange(file); }} /></>}</label>; }
