import { z } from "zod";

const phone = z.string().regex(/^(0|\+84)(3|5|7|8|9)[0-9]{8}$/, "Số điện thoại Việt Nam không hợp lệ");
export const addressSchema = z.object({ recipientName: z.string().min(2).max(80), phone, province: z.string().min(2), district: z.string().min(2), ward: z.string().min(2), addressLine: z.string().min(5).max(220) });
export const registerSchema = z.object({ fullName: z.string().min(2).max(80), email: z.string().email().optional(), phone, password: z.string().min(8).max(100) });
export const loginSchema = z.object({ phone: phone.optional(), email: z.string().email().optional(), password: z.string().min(8) }).refine((value) => value.phone || value.email, "Cần số điện thoại hoặc email");
export const categorySchema = z.object({ parent: z.string().length(24).nullable().optional(), name: z.string().min(2).max(100), slug: z.string().regex(/^[a-z0-9-]+$/), description: z.string().max(1000).default(""), image: z.string().min(0).default(""), bannerImage: z.string().min(0).default(""), detailFields: z.array(z.object({ key: z.string().regex(/^[a-z0-9_]+$/), label: z.string().min(1), type: z.enum(["text", "number", "select", "boolean"]), required: z.boolean().default(false), options: z.array(z.string()).default([]) })).default([]), isActive: z.boolean().default(true), sortOrder: z.number().int().min(0).default(0) });
export const productSchema = z.object({ category: z.string().length(24), name: z.string().min(2).max(180), slug: z.string().regex(/^[a-z0-9-]+$/), shortDescription: z.string().max(300).default(""), description: z.string().max(10000).default(""), price: z.number().int().min(0), salePrice: z.number().int().min(0).optional(), inventory: z.number().int().min(0), sku: z.string().min(3).max(60), images: z.array(z.string()).max(12).default([]), specifications: z.record(z.string(), z.union([z.string(), z.number(), z.boolean()])).default({}), status: z.enum(["draft", "active", "archived"]).default("draft") });
export const orderSchema = z.object({ customer: z.object({ fullName: z.string().min(2).max(80), phone, email: z.string().email().optional() }), shippingAddress: addressSchema, items: z.array(z.object({ productId: z.string().length(24), quantity: z.number().int().min(1).max(20) })).min(1).max(50), note: z.string().max(500).default(""), paymentMethod: z.enum(["cod", "bank_transfer", "vnpay"]).default("cod"), saveAddress: z.boolean().default(false) });
export const reviewSchema = z.object({ productId: z.string().length(24), orderId: z.string().length(24), rating: z.number().int().min(1).max(5), title: z.string().max(120).default(""), body: z.string().min(10).max(2000) });
