import { NextResponse } from "next/server";
import { randomUUID } from "node:crypto";
import { Cart } from "@/models/Cart";
import { catalogRepository } from "@/lib/catalog/repository";
import { connectDb } from "@/lib/server/db";
import { apiError } from "@/lib/server/http";
const cookieName = "toc_tai_cart";
async function getCart(request: Request) { await connectDb(); const token = request.headers.get("x-cart-token") ?? request.headers.get("cookie")?.match(new RegExp(`${cookieName}=([^;]+)`))?.[1] ?? randomUUID(); const cart = await Cart.findOneAndUpdate({ token }, { $setOnInsert: { token, items: [] } }, { upsert: true, new: true }); return { token, cart }; }
async function response(request: Request, data: unknown, status = 200, token?: string) { const result = NextResponse.json({ data }, { status }); if (token) result.cookies.set(cookieName, token, { httpOnly: true, sameSite: "lax", secure: process.env.NODE_ENV === "production", path: "/", maxAge: 60 * 60 * 24 * 30 }); return result; }
export async function GET(request: Request) { try { const { token, cart } = await getCart(request); const items = await Promise.all(cart.items.map(async (item: { productId: string; quantity: number; variantId?: string }) => { const product = await catalogRepository.find(item.productId); return product ? { productId: product.id, name: product.name, price: product.price, quantity: item.quantity, image: product.images[0] ?? "", variantId: item.variantId } : null; })); return response(request, items.filter(Boolean), 200, token); } catch (error) { return apiError(error); } }
export async function POST(request: Request) { try { const { token, cart } = await getCart(request); const body = await request.json() as { productId: string; quantity?: number; variantId?: string }; const product = await catalogRepository.find(body.productId); if (!product) return NextResponse.json({ error: "Product not found" }, { status: 404 }); const quantity = Math.max(1, body.quantity ?? 1); const existing = cart.items.find((item: { productId: string; variantId?: string }) => item.productId === body.productId && item.variantId === body.variantId); if (existing) existing.quantity += quantity; else cart.items.push({ productId: product.id, quantity, variantId: body.variantId }); await cart.save(); return response(request, cart.items, 201, token); } catch (error) { return apiError(error); } }
export async function PATCH(request: Request) { try { const { token, cart } = await getCart(request); const body = await request.json() as { productId: string; quantity: number; variantId?: string }; cart.items = cart.items.filter((item: { productId: string; variantId?: string }) => !(item.productId === body.productId && item.variantId === body.variantId) || body.quantity > 0); const item = cart.items.find((entry: { productId: string; variantId?: string }) => entry.productId === body.productId && entry.variantId === body.variantId); if (item) item.quantity = Math.max(1, body.quantity); await cart.save(); return response(request, cart.items, 200, token); } catch (error) { return apiError(error); } }