"use client";

import { ChevronRight, MapPin, PackageCheck, Search, SlidersHorizontal, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { AdminShell } from "@/components/admin/AdminShell";
import panel from "@/components/admin/admin-panel.module.css";
import { paymentLabel, providerLabel, statusLabel, type OrderStatus, type PaymentStatus, type ShippingProvider } from "@/lib/orderLabels";
import styles from "./orders.module.css";

type OrderItem = { name: string; sku: string; quantity: number; unitPrice: number; image?: string; variantId?: string; variantTitle?: string; options?: { groupTitle: string; optionLabel: string; priceAdjustment?: number }[] };
type Order = { _id: string; orderNumber: string; customer: { fullName: string; phone: string; email?: string }; shippingAddress?: { recipientName: string; phone: string; province: string; district: string; ward: string; addressLine: string }; items: OrderItem[]; total: number; status: OrderStatus; paymentStatus: PaymentStatus; paymentMethod: string; trackingNumber?: string; shippingProvider?: ShippingProvider; createdAt: string };
const money = new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 });
const statusOptions = Object.keys(statusLabel) as OrderStatus[];
const providerOptions = Object.keys(providerLabel) as ShippingProvider[];
const tone: Record<OrderStatus, string> = { pending: "orange", confirmed: "blue", processing: "violet", shipping: "blue", completed: "green", cancelled: "red", returned: "gray" };

export default function AdminOrdersPage() {
  const [orders, setOrders] = useState<Order[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [selected, setSelected] = useState<Order | null>(null);
  const [draft, setDraft] = useState({ status: "pending" as OrderStatus, shippingProvider: "manual" as ShippingProvider, trackingNumber: "" });
  function load() { setLoading(true); fetch("/api/orders").then((response) => response.json()).then((body) => body.data ? setOrders(body.data) : setMessage(body.error ?? "Không tải được đơn hàng")).finally(() => setLoading(false)); }
  useEffect(load, []);
  const filtered = useMemo(() => orders.filter((order) => { const term = search.toLowerCase().trim(); return (!term || [order.orderNumber, order.customer?.fullName, order.customer?.phone].some((value) => value?.toLowerCase().includes(term))) && (status === "all" || order.status === status); }), [orders, search, status]);
  const metrics = { pending: orders.filter((order) => order.status === "pending").length, processing: orders.filter((order) => ["confirmed", "processing"].includes(order.status)).length, shipping: orders.filter((order) => order.status === "shipping").length, revenue: orders.filter((order) => order.status === "completed").reduce((sum, order) => sum + order.total, 0) };
  function open(order: Order) { setSelected(order); setDraft({ status: order.status, shippingProvider: order.shippingProvider ?? "manual", trackingNumber: order.trackingNumber ?? "" }); }
  async function save() { if (!selected) return; setSaving(true); setMessage(""); try { const response = await fetch(`/api/orders/${selected._id}/status`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Cập nhật thất bại"); setOrders((current) => current.map((order) => order._id === selected._id ? body.data : order)); setSelected(null); setMessage(`Đã cập nhật ${selected.orderNumber}.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Cập nhật thất bại"); } finally { setSaving(false); } }
  return <AdminShell breadcrumb="Đơn hàng"><div className={panel.header}><div><p>COMMERCE / ĐƠN HÀNG</p><h1>Quản lý đơn hàng</h1></div></div>
    <section className={styles.metrics}><article><span>CHỜ XÁC NHẬN</span><strong>{metrics.pending}</strong><small>Cần xử lý ngay</small></article><article><span>ĐANG ĐÓNG GÓI</span><strong>{metrics.processing}</strong><small>Đã xác nhận / xử lý</small></article><article><span>ĐANG GIAO</span><strong>{metrics.shipping}</strong><small>Đơn có vận đơn</small></article><article><span>DOANH THU HOÀN TẤT</span><strong>{money.format(metrics.revenue)}</strong><small>Từ đơn hoàn tất</small></article></section>
    <div className={`${panel.panel} ${styles.orderPanel}`}><div className={styles.toolbar}><div className={styles.search}><Search size={18}/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Tìm mã đơn, khách hàng hoặc số điện thoại..." /></div><div className={styles.filter}><SlidersHorizontal size={17}/><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">Tất cả trạng thái</option>{statusOptions.map((value) => <option key={value} value={value}>{statusLabel[value]}</option>)}</select></div><b>{filtered.length} đơn hàng</b></div>
      <div className={panel.tableWrap}><table className={styles.table}><thead><tr><th>Đơn hàng</th><th>Khách hàng</th><th>Thanh toán</th><th>Trạng thái</th><th>Vận chuyển</th><th></th></tr></thead><tbody>{filtered.map((order) => <tr key={order._id}><td><b>{order.orderNumber}</b><small>{new Date(order.createdAt).toLocaleString("vi-VN")}</small><strong>{money.format(order.total)}</strong></td><td><b>{order.customer?.fullName}</b><small>{order.customer?.phone}</small><button className={styles.addressButton} onClick={() => open(order)}><MapPin size={13}/> Xem địa chỉ</button></td><td><span className={`${panel.status} ${order.paymentStatus === "paid" ? panel.green : panel.gray}`}>{paymentLabel[order.paymentStatus]}</span><small>{order.paymentMethod === "cod" ? "Thanh toán khi nhận" : order.paymentMethod}</small></td><td><span className={`${panel.status} ${panel[tone[order.status]]}`}>{statusLabel[order.status]}</span></td><td><b>{order.shippingProvider ? providerLabel[order.shippingProvider] : "Chưa chọn"}</b><small>{order.trackingNumber || "Chưa có mã vận đơn"}</small></td><td><button className={styles.processButton} onClick={() => open(order)}>Xử lý <ChevronRight size={16}/></button></td></tr>)}</tbody></table>{!loading && filtered.length === 0 && <div className={styles.empty}><PackageCheck size={32}/><h3>Chưa có đơn phù hợp</h3><p>Hãy seed đơn mẫu để thử quy trình xử lý.</p></div>}{loading && <p className={panel.empty}>Đang tải đơn hàng…</p>}</div></div>{message && <p className={panel.message}>{message}</p>}
    <aside className={`${styles.drawer} ${selected ? styles.open : ""}`} aria-hidden={!selected}><div className={styles.drawerBody}>{selected && <><header className={styles.drawerHeader}><div><span>ORDER PROCESSING</span><h2>{selected.orderNumber}</h2><p>{selected.customer.fullName} · {money.format(selected.total)}</p></div><button onClick={() => setSelected(null)} aria-label="Đóng"><X size={19}/></button></header><section className={styles.customer}><b>Người nhận</b><p>{selected.shippingAddress?.recipientName || selected.customer.fullName} · {selected.shippingAddress?.phone || selected.customer.phone}</p><p>{[selected.shippingAddress?.addressLine, selected.shippingAddress?.ward, selected.shippingAddress?.district, selected.shippingAddress?.province].filter(Boolean).join(", ") || "Chưa có địa chỉ"}</p></section><section className={styles.items}><b>Sản phẩm ({selected.items?.length ?? 0})</b>{selected.items?.map((item, index) => <div className={styles.orderItem} key={`${item.sku}-${index}`}><span><b>{item.name} × {item.quantity}</b>{item.variantTitle && <em>{item.variantTitle}</em>}{item.options?.length ? <small>{item.options.map((option) => `${option.groupTitle}: ${option.optionLabel}`).join(" · ")}</small> : null}<code>{item.sku}</code></span><strong>{money.format(item.unitPrice * item.quantity)}</strong></div>)}</section><div className={styles.form}><label>Trạng thái đơn<select value={draft.status} onChange={(event) => setDraft((current) => ({ ...current, status: event.target.value as OrderStatus }))}>{statusOptions.map((value) => <option key={value} value={value}>{statusLabel[value]}</option>)}</select></label><label>Đơn vị vận chuyển<select value={draft.shippingProvider} onChange={(event) => setDraft((current) => ({ ...current, shippingProvider: event.target.value as ShippingProvider }))}>{providerOptions.map((value) => <option key={value} value={value}>{providerLabel[value]}</option>)}</select></label><label>Mã vận đơn<input value={draft.trackingNumber} onChange={(event) => setDraft((current) => ({ ...current, trackingNumber: event.target.value }))} placeholder="Ví dụ: GHN123456" /></label></div></>}</div><footer className={styles.drawerFooter}><button onClick={() => setSelected(null)}>Đóng</button><button className={panel.saveButton} disabled={saving} onClick={save}>{saving ? "Đang lưu…" : "Cập nhật đơn"}</button></footer></aside>{selected && <button className={styles.backdrop} onClick={() => setSelected(null)} aria-label="Đóng drawer" />}</AdminShell>;
}
