import Image from "next/image";
import Link from "next/link";
import styles from "./SiteChrome.module.css";
import { FacebookIcon, InstagramIcon, XIcon, YoutubeIcon } from "./SocialIcons";
const groups = [
  { title: "Khám phá & Kiến thức", links: [["Sản phẩm", "/shop/all"], ["Kiểm tra tình trạng tóc", "/pages/hair-form-assessment"], ["Nguyên nhân hói đầu", "/kham-pha/nguyen-nhan-hoi-dau"], ["Cách chữa hói chữ M", "/kham-pha/cach-chua-hoi-dau-chu-m"], ["Giải pháp mọc tóc", "/kham-pha/giai-phap-moc-toc-nhanh"]] },
  { title: "Hỗ trợ khách hàng", links: [["Đổi trả & hoàn tiền", "/chinh-sach-doi-tra"], ["Chính sách giao hàng", "/chinh-sach-giao-hang"], ["Theo dõi đơn hàng", "/account"]] },
  { title: "Về CareWise", links: [["Chính sách bảo mật", "/chinh-sach-bao-mat"], ["Điều khoản dịch vụ", "/dieu-khoan-dich-vu"]] },
] as const;
export function SiteFooter() { return <footer className={`${styles.root} ${styles.footer}`}><div className={styles.footerInner}><div className={styles.footerTop}><div><Image src="/images/logocarewise.png" alt="CareWise" width={1536} height={1024} className={styles.footerLogo} /><p className={styles.footerIntro}>{"Ch\u0103m s\u00f3c t\u00f3c v\u00e0 s\u1ee9c kh\u1ecfe nam gi\u1edbi"}<br />{"\u0110\u01a1n gi\u1ea3n, khoa h\u1ecdc, ph\u00f9 h\u1ee3p v\u1edbi b\u1ea1n."}</p></div><div className={styles.footerCta}><b>{"B\u1eaft \u0111\u1ea7u routine c\u1ee7a b\u1ea1n"}</b><span>{"Kh\u00e1m ph\u00e1 gi\u1ea3i ph\u00e1p ph\u00f9 h\u1ee3p v\u1edbi nhu c\u1ea7u."}</span><Link href="/shop/all">{"Xem s\u1ea3n ph\u1ea9m"} <span aria-hidden="true">-&gt;</span></Link></div></div><div className={styles.footerLinks}>{groups.map((group) => <div className={styles.linkColumn} key={group.title}><h3>{group.title}</h3>{group.links.map(([label, href]) => <Link href={href} key={href}>{label}</Link>)}</div>)}</div><div className={styles.footerBottom}><span>{"(c) 2026 T\u00f3c Tai Studio. B\u1ea3o l\u01b0u m\u1ecdi quy\u1ec1n."}</span><div className={styles.socials}><a href="https://facebook.com" aria-label="Facebook"><FacebookIcon size={16} /></a><a href="https://instagram.com" aria-label="Instagram"><InstagramIcon size={16} /></a><a href="https://twitter.com" aria-label="X"><XIcon size={16} /></a><a href="https://youtube.com" aria-label="YouTube"><YoutubeIcon size={16} /></a></div><Link href="/terms-and-conditions">{"\u0110i\u1ec1u kho\u1ea3n d\u1ecbch v\u1ee5"}</Link></div></div></footer>; }
