import { NextResponse } from "next/server";
import { Order } from "@/models/Order";
import { Cart } from "@/models/Cart";
import { catalogRepository } from "@/lib/catalog/repository";
import { connectDb } from "@/lib/server/db";
import { currentUser } from "@/lib/server/auth";
import { apiError } from "@/lib/server/http";
const cartCookie = "toc_tai_cart";
const orderNumber = () => `TT-${Date.now().toString().slice(-8)}`; const paymentCode = () => `DH${Math.floor(100000 + Math.random() * 900000)}`;
export async function POST(request: Request) { try { await connectDb(); const token = request.headers.get("cookie")?.match(new RegExp(`${cartCookie}=([^;]+)`))?.[1]; if (!token) return NextResponse.json({ error: "Cart is empty" }, { status: 400 }); const cart = await Cart.findOne({ token }); if (!cart?.items.length) return NextResponse.json({ error: "Cart is empty" }, { status: 400 }); const body = await request.json() as { customer: { fullName: string; phone: string; email?: string }; shippingAddress: { recipientName: string; phone: string; province: string; district: string; ward: string; addressLine: string }; paymentMethod: "cod" | "bank_transfer" | "vnpay" | "sepay" }; const items = []; for (const line of cart.items) { const product = await catalogRepository.find(line.productId); if (!product) return NextResponse.json({ error: "Product no longer available" }, { status: 409 }); items.push({ product: null, catalogProductId: product.id, name: product.name, sku: product.sku, quantity: line.quantity, unitPrice: product.price, image: product.images[0] ?? "" }); } const subtotal = items.reduce((sum, item) => sum + item.unitPrice * item.quantity, 0); const shippingFee = subtotal >= 499 ? 0 : 30; const session = await currentUser(); const order = await Order.create({ orderNumber: orderNumber(), user: session?.id ?? null, customer: body.customer, shippingAddress: body.shippingAddress, items, subtotal, shippingFee, total: subtotal + shippingFee, paymentMethod: body.paymentMethod, paymentCode: body.paymentMethod === "sepay" ? paymentCode() : "" }); await Cart.deleteOne({ token }); return NextResponse.json({ data: { ...order.toObject(), paymentCode: order.paymentCode, payment: order.paymentMethod === "sepay" ? { bank: process.env.SEPAY_BANK ?? "", account: process.env.SEPAY_ACCOUNT ?? "", qrUrl: `https://vietqr.app/img?acc=${encodeURIComponent(process.env.SEPAY_ACCOUNT ?? "")}&bank=${encodeURIComponent(process.env.SEPAY_BANK ?? "")}&amount=${order.total}&des=${encodeURIComponent(order.paymentCode)}` } : null } }, { status: 201 }); } catch (error) { return apiError(error); } }